#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Reducing Traffic Mortality in the USA"
description    : >
   How can we find a good strategy for reducing traffic-related deaths?
long_description: |
  While the rate of fatal road accidents has been decreasing steadily since the 80s, the past ten years have seen a stagnation in this reduction. Coupled with the increase in number of miles driven in the nation, the total number of traffic related-fatalities has now reached a ten year high and is rapidly increasing.
  
  By looking at the demographics of traﬃc accident victims for each 
  US state, we find that there is a lot of variation between states. Now we want 
  to understand if there are patterns in this variation in order to derive 
  suggestions for a policy action plan. In particular, instead of implementing a 
  costly nation-wide plan we want to focus on groups of states with similar 
  profiles. How can we find such groups in a statistically sound way and 
  communicate the result effectively?
  
  This project lets you apply skills from:
  
  - [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse), including the pipe operator, summarizing data, and visualizing with ggplot2
  - [Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression), including computing correlations and regression coefficients
  - [Unsupervised Learning in R](https://www.datacamp.com/courses/unsupervised-learning-in-r), including PCA and KMeans clustering.
  
  We recommend that you take these courses before starting this project.
    
time_needed: "60 minutes" # "30/45/60 minutes".

#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 1 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites: 
  - 1498 # Data Visualization in R
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://authoring.datacamp.com/projects/projects-repo-structure.html#project-yml for IDs
topics:
  - 3
  - 4
  - 6
  - 8

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : r # One of r, python or sql
# The name of the docker image used to run the course
from           : 'r-notebooks-tidyverse-prod:v1.0.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.


